# Generated by Django 3.1.5 on 2021-02-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_temp',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=15)),
                ('married', models.CharField(max_length=1)),
                ('connected', models.BooleanField()),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=1000)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_temp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidate.candidate_temp')),
                ('password', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
            ],
            bases=('candidate.candidate_temp',),
        ),
    ]
