# Generated by Django 3.1.5 on 2021-02-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
