# Generated by Django 3.1.5 on 2021-02-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_delete_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=15)),
                ('married', models.CharField(max_length=1)),
                ('connected', models.BooleanField()),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=1000)),
                ('otp', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
