# Generated by Django 3.1.5 on 2021-02-20 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loggedin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authtoken', models.CharField(max_length=25)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
        ),
    ]
