# Generated by Django 3.1.5 on 2021-02-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20210220_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='connected',
            field=models.CharField(max_length=1),
        ),
    ]
